package com.example.java_web_final_project;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Thing {
//    You will model some data of your choosing (in class we used Candy and Songs, for example)
//    This data must have at least two instance fields other than an id
//    This data must have an id field that is automatically generated by Spring Data JPA


        @Id
        @GeneratedValue(strategy= GenerationType.AUTO)
        private Integer id;

        private String name;

        private String description;

        private String imageUrl;



        public Thing() {
        }

        public Thing(String name) {
            this.name = name;
        }

    public Thing(ThingDto thingDto) {

            this.name = thingDto.name;
            this.description = thingDto.description;
            this.imageUrl = thingDto.imageUrl;

        }



        public Integer getId()
        {
            return id;
        }

        public void setId( Integer id )
        {
            this.id = id;
        }

        public String getName()
        {
            return name;
        }

        public void setName( String name )
        {
            this.name = name;
        }

        public String getDescription()
        {
            return description;
        }

        public void setDescription( String description )
        {
            this.description = description;
        }

        public String getImageUrl()
        {
            return imageUrl;
        }

        public void setImageUrl( String imageUrl )
        {
            this.imageUrl = imageUrl;
        }

    @Override
    public String toString() {
        return "Thing{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", imageUrl='" + imageUrl + '\'' +
                '}';
    }
}

